### ISSUE TITLE
Prevent BeamGen from generating already existing edges

### ISSUE THREAD

**Issue by Distrikt64** [50thomatoes50/BlenderBeamNGExport#19]
Currently, BeamGen generates edges even on already existing ones : 

![demo_duplicate_edges](https://user-images.githubusercontent.com/8573006/58857966-c20f8180-86a6-11e9-9186-43d17ff83dbf.gif)

This is not the intended behavior, we should check if the edges we want to add are already existing.

**Comment by 50thomatoes50** [comment]
Blender 2.8 seams to handle better duplicated edges when selecting but it will still generate duplicate beams when exporting.

Will port to bmesh too #32
