### ISSUE TITLE
Rename BeamGen and its class to a more appropriate name

### ISSUE THREAD

**Issue by Distrikt64** [50thomatoes50/BlenderBeamNGExport#20]
Currently, BeamGen doesn't have an explicit name.

This operator is used to connect all selected vertices.
In mathematics, this is equivalent to complete graphs of dimension 3 : https://en.wikipedia.org/wiki/Dimension_(graph_theory)#Complete_graph

New name ideas : 
- NodeConnect
- VertexConnect
- NodeSolidify
- VertexSolidify
- StructureSolidifer
- JBeam Solidifier

**Comment by 50thomatoes50** [comment]
`NodesConnector`
