### ISSUE TITLE
[BeamNG] Monster Jam Suspension Problems

### ISSUE THREAD

**Issue by KK-1701-K** [50thomatoes50/BlenderBeamNGExport#42]
https://www.mediafire.com/file/tj1s8zbd5sp6gav/Anderson_King_Coil-Over_Shocks.blend/file

https://www.mediafire.com/file/vdyy25cwi2zbdjo/Coil-Over_Shocks.blend/file

https://www.mediafire.com/file/igrfn4rcoav1x1a/King_Coil-Over_Shocks.blend/file

https://www.mediafire.com/file/0nlr031fjwq20hm/CRD.zip/file

https://www.mediafire.com/file/ihosjbndmloc4to/CRD_Blz_5.zip/file

https://www.mediafire.com/file/3p1devlqu764bqn/Elbow_Swaybars.zip/file

https://www.mediafire.com/file/jtn09zkuep22e93/Wolverine.blend/file

(sighs) I've been searching YouTube everywhere for a full tutorial which shows me step by step how to mount all coil-over shock packages properly on every last Monster Jam chassis there is for BeamNG thus far; & even today, I find none. I see no member of Beam-Monsters either able or willing to help me, nor do I see myself accomplishing this task at all without help.

In a special competition I had in mind for BeamNG, there was a rule regarding suspension packages. As for any Monster Jam truck featuring coil-over shocks, the coil-over on every last corner of any Monster Jam chassis [produced for BeamNG] belongs in between its assisting nitrogen bypass shock & any sway bar on the front or rear. Sadly, the only coil-over shock packages properly mounted on any Monster Jam chassis produced for BeamNG are those on the rear of both CRD & CRD 3.0 chasses; & to me, that is absolutely unsatisfactory.

If there is indeed a full tutorial which shows me step by step how to mount all coil-over shock packages properly on every last Monster Jam chassis produced for BeamNG, I'm looking for it. Some other changes are in order as well.

Since neither Anderson shock package is properly placed on either differential's mounts, that's why the Anderson sway bars belong in the Adjustable Addons pack; but I see no way to move them from one pack & place them in another. A parsing error prevents me from importing the Anderson nitrogen shocks & the Bigfoot X Cantilevers into Blender as well, & I'm not sure why.

As for the King coil-over shocks, moving each one's hose is the tricky part.

I'm yet to find out how to apply textures to certain items, such as the elbow sway bars (Anderson & CRC (for the CRD chassis)).

And these are .dae, .jbeam, & .json files we're dealing with.

Shown here is how all coil-over shock packages are properly mounted on a CRD chassis; but on BeamNG, that ain't the case at all.
![Coil-Over Shocks](https://github.com/50thomatoes50/BlenderBeamNGExport/assets/96151715/21f6e8b0-bca5-4e38-b391-0d423f4518f5)

It was done in real competition.
![Bad Habit](https://github.com/50thomatoes50/BlenderBeamNGExport/assets/96151715/cb4b6192-a7a8-4b81-990b-22f4e09b296d)
![Gunslinger](https://github.com/50thomatoes50/BlenderBeamNGExport/assets/96151715/a106ceb9-13a8-439f-b3e7-32018843fb8f)
![King Krunch](https://github.com/50thomatoes50/BlenderBeamNGExport/assets/96151715/22117474-f63b-44f5-b60f-5ee8d569b880)

It was done on Rigs of Rods.
https://www.mediafire.com/file/gdfkof284mln3vo/WOLVERINE.mp4/file

But why can't it be done on BeamNG as well?

**Comment by 50thomatoes50** [comment]
The issues system is **not** meant to be used for asking help on using the tool

This addon is only meant as a initial draft when creating a vehicle or prop from scratch.
it has too many limitation and will require tweak by hand later on. It will probably not be helpfull for what you want to do.

I suggest asking for modding support [here](https://discord.gg/3Fy86de) or at [the source of the mod](https://discord.gg/kNqpseGXgK)
